--------------------------------------------------------
--  Fichier créé - dimanche-juillet-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONGE_SPEC
--------------------------------------------------------

  CREATE TABLE "ABDOU"."CONGE_SPEC" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MATRICULE" VARCHAR2(6 BYTE), 
	"TYPE" VARCHAR2(5 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ABDOU.CONGE_SPEC
SET DEFINE OFF;
Insert into ABDOU.CONGE_SPEC (ID,MATRICULE,TYPE,DATE_DEBUT,DATE_FIN) values ('3','00014N','CM',to_date('16/03/21','DD/MM/RR'),to_date('18/03/21','DD/MM/RR'));
Insert into ABDOU.CONGE_SPEC (ID,MATRICULE,TYPE,DATE_DEBUT,DATE_FIN) values ('21','00559K','CM',to_date('15/07/21','DD/MM/RR'),to_date('02/08/21','DD/MM/RR'));
Insert into ABDOU.CONGE_SPEC (ID,MATRICULE,TYPE,DATE_DEBUT,DATE_FIN) values ('1','00256c','CM',to_date('01/07/21','DD/MM/RR'),to_date('07/07/21','DD/MM/RR'));
Insert into ABDOU.CONGE_SPEC (ID,MATRICULE,TYPE,DATE_DEBUT,DATE_FIN) values ('2','00014N','CM',to_date('16/03/21','DD/MM/RR'),to_date('18/03/21','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index CONGE_SPEC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDOU"."CONGE_SPEC_PK" ON "ABDOU"."CONGE_SPEC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONGE_SPEC
--------------------------------------------------------

  ALTER TABLE "ABDOU"."CONGE_SPEC" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ABDOU"."CONGE_SPEC" ADD CONSTRAINT "CONGE_SPEC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
